#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso fluxFunctions
wclean libso fluxIntegrators
wclean libso compressibleSystem

wclean

#------------------------------------------------------------------------------
